// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-conversations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "List chat conversations",
  description: "List the signed-in user's saved chat conversations with Sir Hootington, ordered by most recently updated.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max conversations to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("chat_conversations").select("id, title, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-conversation-messages.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_conversation_messages_default = defineTool2({
  name: "get_conversation_messages",
  title: "Get conversation messages",
  description: "Fetch all messages from one of the signed-in user's chat conversations, in chronological order.",
  inputSchema: {
    conversation_id: z2.string().uuid().describe("The conversation id to load (from list_conversations).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("chat_messages").select("id, user_message, ai_response, emotion, intensity, created_at").eq("user_id", ctx.getUserId()).eq("conversation_id", conversation_id).order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-mbti-result.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_mbti_result_default = defineTool3({
  name: "get_mbti_result",
  title: "Get MBTI personality result",
  description: "Fetch the signed-in user's most recent MBTI personality test result, including their type and axis scores.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("mbti_results").select("personality_type, e_i_score, s_n_score, t_f_score, j_p_score, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "No MBTI result found. Take the personality test in the app first." }],
        structuredContent: { result: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { result: data }
    };
  }
});

// src/lib/mcp/tools/recent-mood.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.57.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var recent_mood_default = defineTool4({
  name: "recent_mood_entries",
  title: "Recent mood entries",
  description: "Fetch the signed-in user's most recent chat messages that logged an emotion and intensity, useful for reviewing mood trends.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("Max entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("chat_messages").select("id, emotion, intensity, user_message, created_at").eq("user_id", ctx.getUserId()).not("emotion", "is", null).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "srbimjnixzhpaiwongli";
var mcp_default = defineMcp({
  name: "mindful-me-mcp",
  title: "MindfulMe",
  version: "0.1.0",
  instructions: "Tools for MindfulMe, a mental wellness companion for youth. Read the signed-in user's chat conversations with Sir Hootington, mood entries, and MBTI personality result to offer supportive, personalized guidance.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_conversations_default, get_conversation_messages_default, get_mbti_result_default, recent_mood_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
